seed = 0
function = "bin.tabr.main"
n_trials = 30
timeout = "__null__"

[sampler]

[space]
seed = 0
batch_size = 256
patience = 16
n_epochs = inf
context_size = 96

[space.data]
seed = 0
cache = true
path = ":data/california"
num_policy = "quantile"
cat_policy = "__null__"
y_policy = "standard"

[space.model]
type = "gate_rm"
num_embeddings = "__null__"
d_embedding = ["_tune_", "int", 96, 384]
n_layers = ["_tune_", "int", 1, 4]
n_ensembles = ["_tune_", "int", 4, 8]
context_dropout = ["_tune_", "uniform", 0.0, 0.6]

[space.optimizer]
type = "AdamW"
lr = ["_tune_", "loguniform", 3e-05, 0.001]
weight_decay = ["_tune_", "?loguniform", 0.0, 1e-06, 0.001]
